# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf < Formula
  desc "Terraform version wrapper"
  homepage "https://github.com/jacobwgillespie/tf"
  version "0.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.1/tf_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "4107c964b8787000c26ca30c6143e3946f1e9cac1bebad9bf3aa166fd4145bea"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.1/tf_0.0.1_Darwin_arm64.tar.gz"
    sha256 "b6274179b0c5149ed8aca05f6ee98323c014fec610e1d5eea46ab3e4298ae4e8"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.1/tf_0.0.1_Linux_x86_64.tar.gz"
    sha256 "68c4126ab3067b171e16a3c62a6b497b703b54378d6a8f98fd0aaebd886a6358"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.1/tf_0.0.1_Linux_arm64.tar.gz"
    sha256 "af6ac74c0851448e74c01c4c791ca581d14e86e063c4499fea0bb49ba5233406"
  end

  def install
    bin.install "tf"
  end
end
