# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf < Formula
  desc "Terraform version wrapper"
  homepage "https://github.com/jacobwgillespie/tf"
  version "0.0.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.3/tf_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "df39f3aa94c6548ddfb41c5f5a008704d2244061f6312e1053b0bd3313c68115"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.3/tf_0.0.3_Darwin_arm64.tar.gz"
    sha256 "55f93c50a7a5c28b1fc6d1b364f51d850bc19ec0967e5839fd63a5edff870766"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.3/tf_0.0.3_Linux_x86_64.tar.gz"
    sha256 "6c6821972e2024a2467f14ad1f6840804c9751302c5720f19d93ef961833ebfa"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.3/tf_0.0.3_Linux_arm64.tar.gz"
    sha256 "43d7fe686e0e043e3823f4b32723b80f02a5a1e0325cfc9bbedba660887c0057"
  end

  def install
    bin.install "tf"
  end
end
