# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf < Formula
  desc "Terraform version wrapper"
  homepage "https://github.com/jacobwgillespie/tf"
  version "0.0.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.2/tf_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "831d5214e3f5255b2a8ad261ffb7f55f61ef1eb94e0d2c9c7ca75a82b4e8a868"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.2/tf_0.0.2_Darwin_arm64.tar.gz"
    sha256 "37460ced78b1d322b10c40f4a7bb314934a808603abf4631ea1ecad46c05c932"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.2/tf_0.0.2_Linux_x86_64.tar.gz"
    sha256 "72d3011084bf8271d2ecbe8cd58ce5a13e51a72c8bcb6ff096af4214e8e25038"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.2/tf_0.0.2_Linux_arm64.tar.gz"
    sha256 "6b3639872c0f0baeb6eedc21cf7ee8633f4740a0af08af801c96574e4a955a34"
  end

  def install
    bin.install "tf"
  end
end
