name: CI

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # - uses: goreleaser/goreleaser-action@v2
      #   if: "!startsWith(github.ref, 'refs/tags/')"
      #   with:
      #     version: latest
      #     args: build --snapshot --rm-dist

      - uses: goreleaser/goreleaser-action@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
